global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['host.docker.internal:50051']

  - job_name: 'product-service'
    static_configs:
      - targets: ['host.docker.internal:50052']

  - job_name: 'order-service'
    static_configs:
      - targets: ['host.docker.internal:50053']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['host.docker.internal:50054']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['host.docker.internal:50055']

  - job_name: 'search-service'
    static_configs:
      - targets: ['host.docker.internal:50056']

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['host.docker.internal:8000']
