spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/todo
    username: root
    password: root

logging:
  level:
    monorepo.services.todo.mapper: debug
