spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/todo
    username: root
    password: root
    datasources:
      - name: reader
        url: jdbc:postgresql://localhost:5432/todo
        username: root
        password: root

management:
  opentelemetry:
    tracing:
      export:
        otlp:
          transport: http
          endpoint: http://localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1
    export:
      enabled: false
  otlp:
    metrics:
      export:
#        url: http://localhost:4318
        enabled: false

logging:
  level:
    monorepo.services.todo.mapper: debug
    monorepo.lib: debug
